"""
DeLorme .dmt export for the KMZ-to-CSV Centerline Generator.

Core machinery (OLE compound-file writer, embedded DeLorme template,
point/line layer templates, coordinate encoding) is copied byte-for-byte
from the proven KMZ-To-DMT-Generator app (github.com/maydenhiller/KMZ-To-DMT-Generator,
blob 52b381e). Only the extraction + centerline-only entry point below are new.

The generated .dmt contains the standard four draw layers (AGMs, Access,
Centerline, Notes); all centerline geometry is written into the Centerline
draw layer (visible in the Draw tab), one polyline per KML LineString, each
keeping its own KML color (fallback red).
"""

# KMZ To DMT Generator  --  single-file Streamlit app.
# Upload a KMZ from the XLSX-To-KMZ Generator; download a DeLorme Street Atlas
# .dmt with four layers: AGMs, Access, Centerline, Notes.

import os
import re
import time
import base64
import zipfile
import struct
import io
import xml.etree.ElementTree as ET




FREESECT   = 0xFFFFFFFF
ENDOFCHAIN = 0xFFFFFFFE
FATSECT    = 0xFFFFFFFD
DIFSECT    = 0xFFFFFFFC
NOSTREAM   = 0xFFFFFFFF
SIG = b'\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1'


class DirEntry:
    __slots__ = ("raw", "name", "type", "color", "left", "right", "child",
                 "start", "size")

    def __init__(self, raw):
        self.raw = bytearray(raw)
        nlen = struct.unpack_from('<H', raw, 64)[0]
        self.name = raw[:max(0, nlen - 2)].decode('utf-16-le') if nlen else ''
        self.type = raw[66]
        self.color = raw[67]
        self.left = struct.unpack_from('<I', raw, 68)[0]
        self.right = struct.unpack_from('<I', raw, 72)[0]
        self.child = struct.unpack_from('<I', raw, 76)[0]
        self.start = struct.unpack_from('<I', raw, 116)[0]
        self.size = struct.unpack_from('<I', raw, 120)[0]

    def set_name(self, name):
        enc = name.encode('utf-16-le')
        assert len(enc) <= 62, "name too long"
        self.raw[0:64] = b'\x00' * 64
        self.raw[0:len(enc)] = enc
        struct.pack_into('<H', self.raw, 64, len(enc) + 2)
        self.name = name

    def pack(self):
        r = bytearray(self.raw)
        r[67] = self.color & 0xFF
        struct.pack_into('<I', r, 68, self.left & 0xFFFFFFFF)
        struct.pack_into('<I', r, 72, self.right & 0xFFFFFFFF)
        struct.pack_into('<I', r, 76, self.child & 0xFFFFFFFF)
        struct.pack_into('<I', r, 116, self.start & 0xFFFFFFFF)
        struct.pack_into('<I', r, 120, self.size & 0xFFFFFFFF)
        struct.pack_into('<I', r, 124, 0)
        return bytes(r)


class OLE:
    def __init__(self, data):
        data = bytes(data)
        assert data[:8] == SIG, "not an OLE compound file"
        self.data = data
        self.sect_size = 1 << struct.unpack_from('<H', data, 30)[0]
        self.mini_size = 1 << struct.unpack_from('<H', data, 32)[0]
        self.dir_start = struct.unpack_from('<I', data, 48)[0]
        self.mini_cutoff = struct.unpack_from('<I', data, 56)[0]
        self.minifat_start = struct.unpack_from('<I', data, 60)[0]
        self.difat_start = struct.unpack_from('<I', data, 68)[0]
        self.num_difat = struct.unpack_from('<I', data, 72)[0]
        self._read_difat()
        self._read_fat()
        self._read_dir()
        self._read_minifat()
        root = self.entries[0]
        self.ministream = self._read_chain(root.start, root.size)

    def _sector(self, i):
        off = 512 + i * self.sect_size
        return self.data[off:off + self.sect_size]

    def _read_difat(self):
        self.difat = []
        for i in range(109):
            v = struct.unpack_from('<I', self.data, 76 + i * 4)[0]
            if v == FREESECT:
                break
            self.difat.append(v)
        sec, n = self.difat_start, self.num_difat
        while sec not in (ENDOFCHAIN, FREESECT) and n > 0:
            s = self._sector(sec)
            for i in range((self.sect_size // 4) - 1):
                v = struct.unpack_from('<I', s, i * 4)[0]
                if v != FREESECT:
                    self.difat.append(v)
            sec = struct.unpack_from('<I', s, self.sect_size - 4)[0]
            n -= 1

    def _read_fat(self):
        self.fat = []
        for sec in self.difat:
            s = self._sector(sec)
            for i in range(self.sect_size // 4):
                self.fat.append(struct.unpack_from('<I', s, i * 4)[0])

    def _chain_sectors(self, start):
        out, s = [], start
        while s not in (ENDOFCHAIN, FREESECT):
            out.append(s)
            s = self.fat[s]
            if len(out) > 2_000_000:
                break
        return out

    def _read_chain(self, start, size):
        return b''.join(self._sector(s) for s in self._chain_sectors(start))[:size]

    def _read_dir(self):
        raw = b''.join(self._sector(s) for s in self._chain_sectors(self.dir_start))
        self.entries = []
        for i in range(0, len(raw), 128):
            e = raw[i:i + 128]
            if len(e) < 128:
                break
            self.entries.append(DirEntry(e))

    def _read_minifat(self):
        if self.minifat_start in (ENDOFCHAIN, FREESECT):
            self.minifat = []
            return
        raw = b''.join(self._sector(s) for s in self._chain_sectors(self.minifat_start))
        self.minifat = [struct.unpack_from('<I', raw, i)[0] for i in range(0, len(raw), 4)]

    def _mini_chain(self, start):
        out, s = [], start
        while s not in (ENDOFCHAIN, FREESECT):
            out.append(s)
            s = self.minifat[s]
            if len(out) > 2_000_000:
                break
        return out

    def read(self, entry):
        if entry.type == 2 and entry.size < self.mini_cutoff:
            return b''.join(
                self.ministream[s * self.mini_size:(s + 1) * self.mini_size]
                for s in self._mini_chain(entry.start))[:entry.size]
        return self._read_chain(entry.start, entry.size)

    def stream_map(self):
        return {e.name: self.read(e) for e in self.entries if e.type == 2}



def _rebuild_directory(entries):
    def child_list(idx):
        out = []
        def inorder(i):
            if i == NOSTREAM or i >= len(entries):
                return
            inorder(entries[i].left)
            out.append(i)
            inorder(entries[i].right)
        inorder(entries[idx].child)
        return out

    # discover parent -> children from the existing tree
    groups = {}
    stack = [0]
    while stack:
        p = stack.pop()
        kids = child_list(p)
        if kids:
            groups[p] = kids
            stack.extend(kids)

    def key(i):
        nm = entries[i].name.upper()
        return (len(entries[i].name), nm)

    def build(idxs):
        if not idxs:
            return NOSTREAM
        mid = len(idxs) // 2
        root = idxs[mid]
        entries[root].left = build(idxs[:mid])
        entries[root].right = build(idxs[mid + 1:])
        entries[root].color = 1  # black
        return root

    for parent, kids in groups.items():
        kids = sorted(kids, key=key)
        entries[parent].child = build(kids)
        entries[parent].color = 1


def write_ole(template, new_streams, rename=None, sect_size=512, mini_size=64, mini_cutoff=4096):
    entries = [DirEntry(bytes(e.raw)) for e in template.entries]

    contents = {}
    for idx, e in enumerate(entries):
        contents[idx] = new_streams.get(e.name, template.read(e)) if e.type == 2 else b''

    # apply renames AFTER content resolution (which keys off original names)
    if rename:
        for e in entries:
            if e.name in rename:
                e.set_name(rename[e.name])
    _rebuild_directory(entries)

    # mini stream: streams smaller than cutoff
    minifat, ministream = [], bytearray()
    for idx, e in enumerate(entries):
        if e.type != 2:
            continue
        data = contents[idx]
        if 0 < len(data) < mini_cutoff:
            nsect = (len(data) + mini_size - 1) // mini_size
            first = len(minifat)
            for j in range(nsect):
                minifat.append(first + j + 1 if j < nsect - 1 else ENDOFCHAIN)
            ministream += data + b'\x00' * (nsect * mini_size - len(data))
            e.start, e.size = first, len(data)
        elif len(data) == 0:
            e.start, e.size = ENDOFCHAIN, 0

    root = entries[0]
    big = [(idx, contents[idx]) for idx, e in enumerate(entries)
           if e.type == 2 and len(contents[idx]) >= mini_cutoff]

    dir_sects = (len(entries) * 128 + sect_size - 1) // sect_size
    minifat_bytes = b''.join(struct.pack('<I', v) for v in minifat)
    minifat_sects = (len(minifat_bytes) + sect_size - 1) // sect_size if minifat else 0
    ministream_sects = (len(ministream) + sect_size - 1) // sect_size if ministream else 0
    big_counts = [(len(d) + sect_size - 1) // sect_size for _, d in big]
    non_fat = dir_sects + minifat_sects + ministream_sects + sum(big_counts)

    fat_sects = 1
    while True:
        needed = ((non_fat + fat_sects) * 4 + sect_size - 1) // sect_size
        if needed <= fat_sects:
            break
        fat_sects = needed

    fat = [FREESECT] * (fat_sects * (sect_size // 4))
    nxt = 0

    def take(n):
        nonlocal nxt
        ids = list(range(nxt, nxt + n))
        nxt += n
        return ids

    def link(ids):
        for k, s in enumerate(ids):
            fat[s] = ids[k + 1] if k < len(ids) - 1 else ENDOFCHAIN

    fat_ids = take(fat_sects)
    dir_ids = take(dir_sects)
    minifat_ids = take(minifat_sects)
    ministream_ids = take(ministream_sects)
    for s in fat_ids:
        fat[s] = FATSECT
    link(dir_ids); link(minifat_ids); link(ministream_ids)

    big_ids = []
    for (idx, data), cnt in zip(big, big_counts):
        ids = take(cnt)
        link(ids)
        entries[idx].start, entries[idx].size = (ids[0] if ids else ENDOFCHAIN), len(data)
        big_ids.append(ids)

    root.start = ministream_ids[0] if ministream_ids else ENDOFCHAIN
    root.size = len(ministream)

    sectors = [b'\x00' * sect_size] * nxt

    def put(ids, data):
        padded = data + b'\x00' * (len(ids) * sect_size - len(data))
        for k, s in enumerate(ids):
            sectors[s] = padded[k * sect_size:(k + 1) * sect_size]

    dir_bytes = b''.join(e.pack() for e in entries)
    if len(dir_bytes) % sect_size:
        dir_bytes += b'\x00' * (sect_size - len(dir_bytes) % sect_size)
    put(dir_ids, dir_bytes)
    if minifat_sects:
        put(minifat_ids, minifat_bytes)
    if ministream_sects:
        put(ministream_ids, bytes(ministream))
    for (idx, data), ids in zip(big, big_ids):
        put(ids, data)
    put(fat_ids, b''.join(struct.pack('<I', v) for v in fat))

    hdr = bytearray(512)
    hdr[0:8] = SIG
    struct.pack_into('<H', hdr, 24, 0x003E)
    struct.pack_into('<H', hdr, 26, 0x0003)
    struct.pack_into('<H', hdr, 28, 0xFFFE)
    struct.pack_into('<H', hdr, 30, 9)
    struct.pack_into('<H', hdr, 32, 6)
    struct.pack_into('<I', hdr, 44, fat_sects)
    struct.pack_into('<I', hdr, 48, dir_ids[0])
    struct.pack_into('<I', hdr, 56, mini_cutoff)
    struct.pack_into('<I', hdr, 60, minifat_ids[0] if minifat_sects else ENDOFCHAIN)
    struct.pack_into('<I', hdr, 64, minifat_sects)
    struct.pack_into('<I', hdr, 68, ENDOFCHAIN)
    for i in range(109):
        struct.pack_into('<I', hdr, 76 + i * 4, fat_ids[i] if i < len(fat_ids) else FREESECT)

    return bytes(hdr) + b''.join(sectors)




KNS = {'k': 'http://www.opengis.net/kml/2.2'}


def _ln(el):
    return el.tag.split('}')[-1]


def _text(el, path):
    f = el.find(path, KNS)
    return f.text.strip() if f is not None and f.text else None


def _coords(s):
    out = []
    for tok in s.replace('\n', ' ').split():
        parts = tok.split(',')
        if len(parts) >= 2:
            out.append((float(parts[0]), float(parts[1])))  # (lon, lat)
    return out


class Placemark:
    def __init__(self, name, kind, coords, icon=None, color=None):
        self.name = name or ''
        self.kind = kind          # 'point' or 'line'
        self.coords = coords      # list of (lon, lat)
        self.icon = icon          # e.g. 'flag.png'
        self.color = color        # KML aabbggrr hex string


def _read_kml_bytes(path_or_bytes):
    if isinstance(path_or_bytes, (bytes, bytearray)):
        zf = zipfile.ZipFile(__import__('io').BytesIO(path_or_bytes))
    else:
        zf = zipfile.ZipFile(path_or_bytes)
    name = next((n for n in zf.namelist() if n.lower().endswith('.kml')), None)
    if name is None:
        raise ValueError("No .kml inside KMZ")
    return zf.read(name)


def parse_kmz(path_or_bytes):
    raw = _read_kml_bytes(path_or_bytes)
    root = ET.fromstring(raw)

    # style id -> (icon file, color)
    styles = {}
    for s in root.iter():
        if _ln(s) == 'Style':
            sid = s.get('id')
            href = s.find('.//k:Icon/k:href', KNS)
            color = s.find('.//k:color', KNS)
            styles[sid] = (
                href.text.split('/')[-1] if href is not None and href.text else None,
                color.text if color is not None else None,
            )

    def style_of(pm):
        su = pm.find('k:styleUrl', KNS)
        if su is not None and su.text:
            return styles.get(su.text.lstrip('#'), (None, None))
        href = pm.find('.//k:Icon/k:href', KNS)
        color = pm.find('.//k:color', KNS)
        return (href.text.split('/')[-1] if href is not None and href.text else None,
                color.text if color is not None else None)

    folders = {}

    # Any Folder anywhere in the tree that directly holds placemarks is a layer.
    for f in root.iter():
        if _ln(f) != 'Folder':
            continue
        fname = _text(f, 'k:name') or 'Folder'
        items = []
        for pm in f.findall('k:Placemark', KNS):
            nm = _text(pm, 'k:name')
            icon, color = style_of(pm)
            pt = pm.find('.//k:Point/k:coordinates', KNS)
            ls = pm.find('.//k:LineString/k:coordinates', KNS)
            if pt is not None and pt.text:
                items.append(Placemark(nm, 'point', _coords(pt.text), icon, color))
            elif ls is not None and ls.text:
                items.append(Placemark(nm, 'line', _coords(ls.text), icon, color))
        if items:
            folders[fname] = items
    return folders



_TEMPLATE_B64 = """
0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAPgADAP7/CQAGAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAEAAACAAAAAEAAAD+////AAAA
AAAAAAD/////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////9////AgAAAAMAAAAE
AAAABQAAAAYAAAAHAAAA/v////7///8KAAAACwAAAAwAAAANAAAA/v///w8AAAAQAAAAEQAAABIAAAATAAAAFAAAABUAAAAWAAAA
FwAAABgAAAAZAAAAGgAAABsAAAAcAAAAHQAAAB4AAAAfAAAAIAAAACEAAAAiAAAAIwAAACQAAAAlAAAAJgAAACcAAAAoAAAAKQAA
ACoAAAArAAAALAAAAC0AAAAuAAAALwAAADAAAAAxAAAAMgAAADMAAAA0AAAANQAAADYAAAA3AAAAOAAAADkAAAA6AAAAOwAAADwA
AAA9AAAAPgAAAD8AAABAAAAAQQAAAEIAAABDAAAARAAAAEUAAABGAAAA/v//////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////1IAbwBvAHQAIABFAG4AdAByAHkAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAUB//////////8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAOCvyeI20dwBCQAAAMAIAAAAAAAARABlAEwAbwByAG0AZQBDAG8AbQBwAG8AbgBlAG4AdABzAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACQAAQH//////////xQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOA+x+I20dwB4K/J4jbR3AEAAAAAAAAA
AAAAAABEAGUATABvAHIAbQBlAC4AQQBuAG4AbwB0AGEAdABlAC4AVwBvAHIAawBzAHAAYQBjAGUAAAAAAAAAAAAAAAAANgABAf//
////////AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4D7H4jbR3AHgr8niNtHcAQAAAAAAAAAAAAAAAEEAbgBuAG8AdABhAHQAZQAu
AEYAaQBsAGUAbgBhAG0AZQBzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmAAIBBwAAAAYAAAD/////AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJIAAAAAAAAAQwBlAG4AdABlAHIAbABpAG4AZQA0ADEAIAAoADQAKQAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIAAgH///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAADAAAAkwAAAAAAAABuAG8AdABlAHMAIAAoADIANgApAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAFgACAf///////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAACzAAAAAAAAAEMAbwBtAGIA
aQBuAGUAZAAgAEEAYwBjAGUAcwBzACAARgBpAGwAZQBzADEAIAAoADEAMQApAAAAAAAAAAAAAAA4AAIBCAAAAP//////////AAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQAAAJMAAAAAAAAARgBpAG4AYQBsACAAQQBHAE0AcwA2ADgAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoAAgEFAAAABAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAOAAAAj3EAAAAAAABBAG4AbgBvAHQAYQB0AGUALgBBAGMAdABpAHYAZQBGAGkAbABlAG4AYQBtAGUAcwAAAAAA
AAAAAAAAAAAAAAAAMgACAf///////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAtAAAAAAAA
AEQAZQBMAG8AcgBtAGUALgBBAHUAdABvAE4AYQB2AC4AVwBvAHIAawBzAHAAYQBjAGUAAAAAAAAAAAAAAAAAAAA0AAEBFwAAAAIA
AAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgr8niNtHcAeCvyeI20dwBAAAAAAAAAAAAAAAARABlAEwAbwByAG0AZQBBAHUAdABv
AE4AYQB2AEYAaQBsAGUAcwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAgH///////////////8AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAGAAAAAAAAABEAGUATABvAHIAbQBlAC4ATQBhAHAAMgBEAC4AMQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAIAABAf//////////DQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4K/J4jbR3AHgr8niNtHcAQAA
AAAAAAAAAAAAAE0AYQBwADIARABTAHQAYQB0AGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW
AAIB////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAADYAAAAAAAAATQBhAHAAMgBEAFMA
dABhAHQAZQAyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAgEMAAAA//////////8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAANgAAAAAAAABEAGUATABvAHIAbQBlAC4AUAByAGUAZgBlAHIAZQBuAGMA
ZQBzAC4AMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAABAf//////////DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4K/J4jbR3AHg
r8niNtHcAQAAAAAAAAAAAAAAAFAAcgBlAGYAQwB1AHIAcgBlAG4AdABTAGUAdAB0AGkAbgBnAHMAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAoAAIB////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAKsDAAAAAAAARABl
AEwAbwByAG0AZQAuAFAAcgBpAG4AdAAyAC4AMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIAAQELAAAADgAAABEA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAOCvyeI20dwB4K/J4jbR3AEAAAAAAAAAAAAAAABQAGEAZwBlAEkAbgBmAG8AAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgACARMAAAASAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAB8AAAAoAAAAAAAAAE8AYgBqAGUAYwB0AEMAbwB1AG4AdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAYAAIB////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAgA
AAAAAAAATwBiAGoAZQBjAHQAcwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAQH/
//////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAOCvyeI20dwB4K/J4jbR3AEAAAAAAAAAAAAAAABEAGUATABvAHIAbQBlAC4A
VABhAHIAZwBlAHQAVABvAG8AbABzAC4AMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAABARAAAAAJAAAAFQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA4K/J4jbR3AHgr8niNtHcAQAAAAAAAAAAAAAAAFQAbwBvAGwAQwBsAGEAcwBzAFMAdABvAHIAYQBnAGUAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiAAEB//////////8WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgr8niNtHcAeCvyeI2
0dwBAAAAAAAAAAAAAAAATQBhAHAAMgBEAE0AZQBhAHMAdQByAGUAVABvAG8AbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAACIAAgH///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhAAAADAAAAAAAAABEAGUATABv
AHIAbQBlAC4AWABEAGEAdABhAC4AVwBvAHIAawBzAHAAYQBjAGUAAAAAAAAAAAAAAAAAAAAAAAAAMAABAf//////////GAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA4K/J4jbR3AHgr8niNtHcAQAAAAAAAAAAAAAAAFgARABhAHQAYQAuAEYAaQBsAGUAbgBhAG0AZQBz
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAIB////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAIgAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////
/////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAIAAAD+////BAAAAAUAAAD+////BwAAAAgAAAD+////CgAAAAsA
AAD+/////v////7////+/////v///xEAAAASAAAAEwAAABQAAAAVAAAAFgAAABcAAAAYAAAAGQAAABoAAAAbAAAAHAAAAB0AAAAe
AAAA/v////7////+/////v////7///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAJQAAAEM6XERlTG9ybWUgRG9jc1xEcmF3XEZpbmFsIEFHTXM2OC5hbjEEAAAAEAAAAENl
bnRlcmxpbmU0MSAoNCkBAAAACgAAAG5vdGVzICgyNikBAAAAGwAAAENvbWJpbmVkIEFjY2VzcyBGaWxlczEgKDExKQEAAAAMAAAA
RmluYWwgQUdNczY4AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACPAAAAJS0AAAAAAAAC
AAAAAAACAAEAAAAOAABBEScAAAAAAAACAAIAAAAXAAABAAAAAADq6olpAAAAAOrqiWkAAAAAAgAAAAAA/wAAAAMAAAAAAAAAAAAA
AAAAAAACAAIAAAABAAAAAADUGcdQU6ZwbAAAAQAAAAAAvBrHUGmlcGwAAAQAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACvAAAAJS0AAAAAAAACAAEAAAABAAAAAAB77VVRVPLlawYAzv///xQAAAANAABB
1icAAA4BBAAAAAAAAAAAACIAQnVja2V5ZSBLZXkAAQAAAAAAgGLhaQAAAACFYuFpAAAAAAUAQXJpYWwAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAKAAAAAAAAAAAAAAADAAAA////AAAAAAADAAAAAgAAAAAABAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAACPAAAA
JS0AAAAAAAACAAAAAAACAAEAAAAPAABBJnYAAAAAAAACAAIAAAAXAAABAAAAAAATT+JpAAAAABNP4mkAAAAAAgAAAAAAAAD/AAMA
AAAAAAAAAAAAAAAAAAACAAIAAAABAAAAAABdqORQAFIfbAAAAQAAAAAAVKjkUBFSH2wAAAQAAAAAAAAAAwAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAJQAAAEM6XERlTG9ybWUgRG9jc1xEcmF3XEZpbmFsIEFH
TXM2OC5hbjEAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAtMgwAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAIAAABosEJRALAJbAYAAABVVVVVVVX1PwAAAAAAAPA/AAAAAAAAAIABEQAAAGiwQlEAsAlsAAAAAAAA
AAAAAAACAAAAaLBCUQCwCWwGAAAAVVVVVVVV9T8AAAAAAADwPwAAAAAAAACAAREAAABosEJRALAJbAAAAAAAAAAAAAAABAAAAAYA
AAB0JwAAAAAAABQnAAABAAAAEycAAAEAAAASJwAAAQAAABEnAAABAAAAJCcAACUnAAAAAAAAtQAAAEJhc2UgTWFwLEJ1c2luZXNz
IFBvaW50cyBvZiBJbnRlcmVzdCAoTWFqb3IpLENvdW50eSBCb3JkZXJzLEV4aXRzLEludGVybmF0aW9uYWwgTGFiZWxzLFBsYWNl
cyAoTWlub3IpLFBvaW50cyBvZiBJbnRlcmVzdCAoTWFqb3IpLFJvYWRzIChNaW5vciksVXJiYW4gQXJlYSBDb2xvciwtRE1MX0NV
U1RPTV9GSUxURVJfSUQAAAAAAAAAAFY0ErCchuZAAAAAAE5iPkE9AAAAEzyBCBQ8gQgWPIEIFzyBCCE8gQgiPIEIJDyBCCU8gQgn
PIEIMDyBCEA8gQhQPIEIYDyBCJA8gQjyPIEI8zyBCPc8gQj4PIEI/DyBCP08gQj/PIEIAT2BCAQ9gQggPYEIUD2BCHE9gQhyPYEI
cz2BCHQ9gQh1PYEIdj2BCHc9gQjgPYEIAj6BCCBEgQgwRIEIUESBCGBEgQgASIEIAEyBCAAYAhEADAUREBAFEQAADhEACA8REBSD
EQBQgxEQBIURIASFETAEhRFABIURUASFEXAEhRGABIURAACKEVEIixFgCIsREQSMETEEjBEAAI8RAACEGEYAAABTb2Z0d2FyZVxE
ZUxvcm1lXFNBMjAxNVxEZUxvcm1lQ29tcG9uZW50c1xEZUxvcm1lLlNBMjAxNS5QcmVmZXJlbmNlcy4xIwAAAERlTG9ybWUgU3Ry
ZWV0IEF0bGFzIFVTQa4gMjAxNSBQbHVzJQEAAEdyaWRzLCBNYXAgQ2VudGVyIENyb3NzaGFpciwgRXhpdHMsIE9uZSBXYXlzLCBQ
bGFjZXMgKE1pbm9yKSwgUm9hZHMgKE1pbm9yKSwgUG9pbnRzIG9mIEludGVyZXN0IChNYWpvciksIFBvaW50cyBvZiBJbnRlcmVz
dCAoTWlub3IpLCBCdXNpbmVzcyBQb2ludHMgb2YgSW50ZXJlc3QgKE1ham9yKSwgQnVzaW5lc3MgUG9pbnRzIG9mIEludGVyZXN0
IChNaW5vciksIFRvd24gQm9yZGVycywgQ291bnR5IEJvcmRlcnMsIEludGVybmF0aW9uYWwgTGFiZWxzLCBVcmJhbiBBcmVhIENv
bG9yLCBaSVAtUG9zdGFsIENvZGVzCAAAAEJhc2UgTWFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAdQAAAAAAAACNAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAawAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAi3EAACUtAAADAAAASUwBAQMAAwABABgAGAD/////IAD//////////0JNNgAA
AAAAAAA2AAAAKAAAAGAAAAAwAAAAAQAYAAAAAAAANgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////////////////////////////
//////////////////////////////////////////////////////////8A//8A//8A//////////////////8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8A//8A//8A//8A/////xQUGhoaGf////8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A/////wAAALAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAg
cLAgcLAgcLAgcAAAAP////8A//8A//8A//8A/////xkZHxkZGf////8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAP8A//8A/////wAAALAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcAAAAP//
//8A//8A//8A//8A//8A/////xoaIBkZGP////8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A//8A//8A
//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AP8A//8A/////wAAALAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcAAAAP////8A//8A//8A//8A
//8A/////xoaIBkZGP////8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A/wAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A////
/wAAALAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcAAAAP////8A//8A//8A//8A//8A//8A/////wAAAAAA
AP////8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
/wAAAAAAAJAAEowAFIYAF34AGncAHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A/////wAAALAgcLAgcLAg
cLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcAAAAP////8A//8A//8A//8A//8A//8A/////wAAAAAAAP////8A//8A//8A
//8A//////////////////////////////////////////////8A//8A//8A//8A//8A//8A//8A//8A//8A/6oABqsABakABqUA
CJwADJIAEYcAFnwAGnMAHgAAAAAAAAAAAP8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A//8A/////wAAALAgcLAgcLAgcLAgcLAgcLAg
cLAgcLAgcLAgcLAgcLAgcAAAAP////8A//8A//8A//8A//8A//8A//8A/////wAAAAAAAP///////////////////////x8fHgAA
AAAAAQAABAAACgAADwAADwAAACQkI/////8A//8A//8A//8A//8A//8A//8A//8A/78AAMUAAMcAAMUAAL8AALYAAKkABZoADYwA
FH4AGnMAHv8A//8A//8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A//8A/////wAAALAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAg
cLAgcAAAAP////8A//8A//8A//8A//8A//8A//8A/////wAAAAAAAB0dEycnGSQkEyQkDycnDx8fCgUFAAAANgAAhgAAmAAAvwAA
3wAA6gAAVCQkEf////8A//8A//8A//8A//8A//8A//8A/88AANkAAN8AAOEAAN8AANkAAM8AAMEAALAAA54AC4wAFHwAG3MAHv8A
//8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAP8A//8A//8A//8A//8A/////wAAALAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcAAAAP////8A//8A
//8A//8A//8A//8A//8A//8A/////wAAAAAAAAAAJQAAPgAATwAAZAAAaQAAawAAegAAiwAApQAAxgAA7QAA/wAA/wAAaCQkDv//
//8A//8A//8A//8A//8A//8A//8A/+QAAO4AAPQAAPUAAPUAAO8AAOUAANcAAMUAALAAApsADIcAFncAHP8A//8A//8A//8A//8A
//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAP8A//8A//8A//8A//8A/////wAAALAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcLAgcAAAAP////8A//8A//8A//8A//8A//8A
//8A//8A/////wAAAAAAAAAAfgAAvwAA2gAA+QAA/wAA/wAA/wAAwwAAiwAAsQAA5AAA/wAA/wAAaCQkDv////8A//8A//8A//8A
//8A//8A/+gAAPYAAP0AAP8FBf8JCP8GBf4AAPUAAOkAANcAAMEAAKkABZIAEX8AGnMAHv8A//8A//8A//8A//8A//8A/wAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A
//8A//8A//8A/////wAAALAgcLAgcLAgcLAgcLAgcLAgcLAgcAAAAP////8A//8A//8A//8A//8A//8A//8A//8A//8A/////wAA
AAAACAAAdgAAsQAAzwAA9wAA/wAA/wAA/wAAwwAAiwAAsQAA5AAA/wAA/wAAaCQkDv////8A//8A//8A//8A//8A//8A//YAAP8D
Av8XFf8pJv8wLv8oJv8WFf8DA/UAAOUAAM8AALUAAJwADIUAF3UAHv8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A//8A//8A//8A////
/wAAALAgcLAgcLAgcLAgcLAgcLAgcLAgcAAAAP////8A//8A//8A//8A//8A//8A//8A//8A//8A/////wAAAAAACAAAdAAArgAA
zAAA9wAA/wAA/wAA/wAAwwAAiwAAsQAA5AAA/wAA/wAAaCQkDv////8A//8A//8A//8A//8A//8A//4AAP8XFf84Nv9WU/9iYP9W
U/84Nf8XFf4AAO4AANkAAL8AAKQACIwAE3kAHf8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A//8A//8A//8A//8A/////wAAALAgcLAg
cLAgcLAgcLAgcAAAAP////8A//8A//8A//8A//8A//8A//8A//8A//8A//8A/////wAAAAAACAAAdAAArgAAzAAA9wAA/wAA/wAA
/wAAwwAAiwAAsQAA5AAA/wAA/wAAaCQkDv////8A//8A//8A//8A//8A//8A//8GBf8oJ/9WU/+Hhv+/v/+Hhv9VVP8oJv8GBfQA
AN8AAMQAAKkABo8AEXsAHP8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A//8A//8A//8A//8A/////wAAALAgcLAgcLAgcLAgcLAgcAAA
AP////8A//8A//8A//8A//8A//8A//8A//8A//8A//8A/////wAAAAAACAAAdAAArgAAzAAA9wAA/wAA/wAA/wAAwwAAiwAAsQAA
5AAA/wAA/wAAaCQkDv////8A//8A//8A//8A//8A//8A//8JCf8wLf9iYP/Av/7+/v/Av/9iYP8wLv8JCPYAAOEAAMcAAKsABZEA
EXwAG/8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A//8A//8A//8A//8A//8A/////wAAALAgcLAgcLAgcAAAAP////8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A/////wAAAAAACAAAdAAArgAAzAAA9wAA/wAA/wAA/wAAyQAAmgAAxAAA7QAA/wAA/wAAaCQk
Dv////8A//8A//8A//8A//8A//8A//8A//8oJv9VVP+Hhv/Av/+Hhf9WU/8oJ/8GBvQAAN8AAMUAAKkABpAAEf8A//8A//8A//8A
//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAP8A//8A//8A//8A//8A//8A//8A//8A/////wAAALAgcLAgcLAgcAAAAP////8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A/////wAAAAAACAAAdgAAsQAAzwAA9wAA/wAA/wAA/wAAugAAdAAAlAAAvwAA3wAA6gAAVCQkEf////8A//8A//8A
//8A//8A//8A//8A//8WFf83Nf9VU/9iYP9WVP84Nv8XFf4AAO4AANkAAL8AAKQACIwAFP8A//8A//8A//8A//8A//8A//8A/wAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A
//8A//8A//8A//8A//8A//8A//8A/////wAAALAgcAAAAP////8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A////
/wAAAAAACQAAfgAAvwAA2gAA+QAA/wAA/wAA/wAAiwAAAAAAAgAACAAADwAADwAAACQkI/////8A//8A//8A//8A//8A//8A//8A
//8A//8XFf8pJ/8wLf8oJv8XFf8DAvUAAOUAAM8AALYAAJwADP8A//8A//8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A//8A//8A//8A
//8A//8A//8A/////wAAALAgcAAAAP////8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A/////wAAAAAAAAAAJQAA
PgAATwAAZAAAawAAagAAcQAAKhISB/////////////////////////////8A//8A//8A//8A//8A//8A//8A//8A//8A//8GBf8K
CP8GBf0AAPYAAOkAANcAAMEAAKoABv8A//8A//8A//8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
/////wAAAP////8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A/////wAAAAAAAB0dEycnGSQkEyQkDyQkDSQk
DiQkDA8PBAAAAP////8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//QAAO4AAOUAANcA
AMUAAP8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A//8A//8A//8A//8A//8A//8A//8A/////wAAAP////8A
//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A/////wAAABUVFP//////////////////////////////////////
//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//////8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A//8A//////////////////8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAP8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//////8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A
/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAElM
AQEDAAMAAQAYABgA/////yEA//////////9CTTYAAAAAAAAANgAAACgAAABgAAAAMAAAAAEAGAAAAAAAADYAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAD///////////////////////////////////////////////////////////////////////////////////////////8A
AAAAAAAAAAD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAD///8U
FBoaGhn///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAACwIHCwIHCwIHCw
IHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHAAAAD///8AAAAAAAAAAAAAAAD///8ZGR8ZGRn///8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAACwIHCwIHCwIHCwIHCwIHCwIHCw
IHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHAAAAD///8AAAAAAAAAAAAAAAAAAAD///8aGiAZGRj///8AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAACwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCw
IHCwIHCwIHCwIHCwIHAAAAD///8AAAAAAAAAAAAAAAAAAAD///8aGiAZGRj///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAACwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHAA
AAD///8AAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQABKMABSGABd+ABp3AB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAD///8AAACwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHAAAAD///8AAAAAAAAA
AAAAAAAAAAAAAAD///8AAAAAAAD///8AAAAAAAAAAAAAAAD///////////////////////////////////////////8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAACqAAarAAWpAAalAAicAAySABGHABZ8ABpzAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAD///8AAACwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD/
//8AAAAAAAD///////////////////////8fHx4AAAAAAAEAAAQAAAoAAA8AAA8AAAAkJCP///8AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAC/AADFAADHAADFAAC/AAC2AACpAAWaAA2MABR+ABpzAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A
AACwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHCwIHAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAdHRMn
JxkkJBMkJA8nJw8fHwoFBQAAADYAAIYAAJgAAL8AAN8AAOoAAFQkJBH///8AAAAAAAAAAAAAAAAAAAAAAAAAAADPAADZAADfAADh
AADfAADZAADPAADBAACwAAOeAAuMABR8ABtzAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAACwIHCwIHCw
IHCwIHCwIHCwIHCwIHCwIHCwIHAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAAACUAAD4AAE8AAGQAAGkA
AGsAAHoAAIsAAKUAAMYAAO0AAP8AAP8AAGgkJA7///8AAAAAAAAAAAAAAAAAAAAAAAAAAADkAADuAAD0AAD1AAD1AADvAADlAADX
AADFAACwAAKbAAyHABZ3ABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAACwIHCwIHCwIHCwIHCwIHCwIHCw
IHCwIHCwIHAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAAAH4AAL8AANoAAPkAAP8AAP8AAP8AAMMAAIsA
ALEAAOQAAP8AAP8AAGgkJA7///8AAAAAAAAAAAAAAAAAAAAAAADoAAD2AAD9AAD/BQX/CQj/BgX+AAD1AADpAADXAADBAACpAAWS
ABF/ABpzAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAACwIHCwIHCwIHCwIHCwIHCwIHCwIHAAAAD///8A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAgAAHYAALEAAM8AAPcAAP8AAP8AAP8AAMMAAIsAALEAAOQAAP8AAP8A
AGgkJA7///8AAAAAAAAAAAAAAAAAAAAAAAD2AAD/AwL/FxX/KSb/MC7/KCb/FhX/AwP1AADlAADPAAC1AACcAAyFABd1AB4AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAACwIHCwIHCwIHCwIHCwIHCwIHCwIHAAAAD///8AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAD///8AAAAAAAgAAHQAAK4AAMwAAPcAAP8AAP8AAP8AAMMAAIsAALEAAOQAAP8AAP8AAGgkJA7///8AAAAA
AAAAAAAAAAAAAAAAAAD+AAD/FxX/ODb/VlP/YmD/VlP/ODX/FxX+AADuAADZAAC/AACkAAiMABN5AB0AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAACwIHCwIHCwIHCwIHCwIHAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAD///8AAAAAAAgAAHQAAK4AAMwAAPcAAP8AAP8AAP8AAMMAAIsAALEAAOQAAP8AAP8AAGgkJA7///8AAAAAAAAAAAAAAAAAAAAA
AAD/BgX/KCf/VlP/h4b/v7//h4b/VVT/KCb/BgX0AADfAADEAACpAAaPABF7ABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAD///8AAACwIHCwIHCwIHCwIHCwIHAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAgA
AHQAAK4AAMwAAPcAAP8AAP8AAP8AAMMAAIsAALEAAOQAAP8AAP8AAGgkJA7///8AAAAAAAAAAAAAAAAAAAAAAAD/CQn/MC3/YmD/
wL/+/v7/wL//YmD/MC7/CQj2AADhAADHAACrAAWRABF8ABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/
//8AAACwIHCwIHCwIHAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAgAAHQAAK4AAMwAAPcA
AP8AAP8AAP8AAMkAAJoAAMQAAO0AAP8AAP8AAGgkJA7///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD/KCb/VVT/h4b/wL//h4X/VlP/
KCf/Bgb0AADfAADFAACpAAaQABEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAACwIHCwIHCw
IHAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAgAAHYAALEAAM8AAPcAAP8AAP8AAP8AALoA
AHQAAJQAAL8AAN8AAOoAAFQkJBH///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD/FhX/NzX/VVP/YmD/VlT/ODb/FxX+AADuAADZAAC/
AACkAAiMABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAACwIHAAAAD///8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAkAAH4AAL8AANoAAPkAAP8AAP8AAP8AAIsAAAAAAAIAAAgAAA8A
AA8AAAAkJCP///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/FxX/KSf/MC3/KCb/FxX/AwL1AADlAADPAAC2AACcAAwAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAACwIHAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAAACUAAD4AAE8AAGQAAGsAAGoAAHEAACoSEgf///////////////////////////8A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/BgX/Cgj/BgX9AAD2AADpAADXAADBAACqAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAD///8AAAAAAAAdHRMnJxkkJBMkJA8kJA0kJA4kJAwPDwQAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAD0AADuAADlAADXAADFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAV
FRT///////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/
//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCTT4AAAAAAAAAPgAAACgAAABgAAAAMAAAAAEAAQAAAAAAQAIAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAP///////////wAAAAAAAcP//////wAAAIAAA8P//////wAAAIAAA8P//////wAAAMAAB8P///+APwAAAMAAB8P///wABwAA
AOAAD8P///wABwAAAOAAD8PAB/wAPwAAAPAAH8AAB/gA/wAAAPAAH8AAB/AAfwAAAPgAP8AAB/AAfwAAAPgAP8AAB+AAPwAAAPwA
f8AAB+AAPwAAAPwAf8AAB+AAPwAAAP4A/8AAB+AAPwAAAP4A/8AAB+AAPwAAAP8B/8AAB/AAfwAAAP8B/8AAB/AAfwAAAP+D/8AA
B/gA/wAAAP+D/8AAB/wB/wAAAP/H/8AB//8H/wAAAP/H/8AB/////wAAAP/v/8P//////wAAAP/v/////////wAAAAsAAAAPAAAA
PwIAAIpKvCA02GxBkT11TtC0wVcPUHVycGxlIFRyaWFuZ2xlBAAAABYAAAA/AgAAWkq8IDTYbEGRPXVO0LTBVwhSZWQgRmxhZwoA
AAAKAAAAPwIAAG5KvCA02GxBkT11TtC0wVcIQmx1ZSBEb3QCAAMAAAABAAAAAAD4NhJIyJOaawEAAAAAAAAAAAABAAFBEScAAA0B
BAAAAAAAAAAAADYAUHVycGxlIFRyaWFuZ2xlAAEAAAAAAJf2L2oAAAAAo/YvagAAAAAAAAAAAAAAAAAAAAAAAP//BQBBcmlhbIpK
vCA02GxBkT11TtC0wVcAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAD4KRJIsIybawEAAAAAAAAAAAAC
AAFBEicAAA0BBAAAAAAAAAAAAC8AUmVkIEZsYWcAAQAAAAAApvYvagAAAACs9i9qAAAAAAAAAAAAAAAAAAAAAAAA//8FAEFyaWFs
Wkq8IDTYbEGRPXVO0LTBVwAAAAAAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAANQ4EkiIpJxrAQAAAAAAAAAA
AAMAAUETJwAADQEEAAAAAAAAAAAALwBCbHVlIERvdAABAAAAAAC69i9qAAAAAL/2L2oAAAAAAAAAAAAAAAAAAAAAAAD//wUAQXJp
YWxuSrwgNNhsQZE9dU7QtMFXAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAABAAAAAAAAAADAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
"""

def _template_bytes():
    return base64.b64decode(_TEMPLATE_B64)






# KMZ folder -> template stream name (Stanley-based template).
LAYER_STREAMS = {
    'AGMs':       'Final AGMs68',
    'Centerline': 'Centerline41 (4)',
    'Notes':      'notes (26)',
    'Access':     'Combined Access Files1 (11)',
}

S23 = 1 << 23
S31 = 1 << 31


def enc(lon, lat):
    return ((round(lon * S23) + S31) & 0xFFFFFFFF,
            (S31 - round(lat * S23)) & 0xFFFFFFFF)


# --- colour names -> RGB (DeLorme stores COLORREF bytes R,G,B,0) ----------
def kml_color_to_rgb(kml):
    if not kml or len(kml) < 8:
        return None
    try:
        bb = int(kml[2:4], 16); gg = int(kml[4:6], 16); rr = int(kml[6:8], 16)
        return (rr, gg, bb)
    except ValueError:
        return None


# --- imagelist colour sniffing: which symbol value is which shape ---------
def _detect_symval_shapes(layer):
    bm = layer.find(b'BM')
    if bm < 0:
        return {}
    try:
        w = struct.unpack_from('<i', layer, bm + 18)[0]
        h = struct.unpack_from('<i', layer, bm + 22)[0]
        bpp = struct.unpack_from('<H', layer, bm + 28)[0]
        off = struct.unpack_from('<I', layer, bm + 10)[0]
    except struct.error:
        return {}
    if bpp != 24 or w <= 0 or h <= 0:
        return {}
    row = ((w * bpp + 31) // 32) * 4
    pix = layer[bm + off: bm + off + row * h]
    shapes = {}
    ntiles = w // 24
    for t in range(ntiles):
        purple = red = blue = 0
        for y in range(h):
            base = y * row
            for x in range(t * 24, min((t + 1) * 24, w)):
                o = base + x * 3
                if o + 2 >= len(pix):
                    continue
                b, g, r = pix[o], pix[o + 1], pix[o + 2]
                if (r, g, b) == (255, 0, 255):      # magenta = transparent
                    continue
                if b > 140 and r < 100 and g < 110:    # blue (circle)
                    blue += 1
                elif r > 100 and b > 120 and g < 110:  # purple (triangle)
                    purple += 1
                elif r > 150 and g < 100 and b < 100:   # red (flag)
                    red += 1
        best = max((blue, 'circle'), (purple, 'triangle'), (red, 'flag'))
        if best[0] > 0:
            shapes[t + 1] = best[1]
    return shapes


# ----------------------------------------------------------------------------
# Point layer template (AGMs / Notes)
# ----------------------------------------------------------------------------
class PointLayerTemplate:
    MARKER = b'\x01\x00\x00\x00\x00\x00'
    SUFFIX_LEN = {True: 97, False: 81}

    def __init__(self, data, has_symbol):
        self.has_symbol = has_symbol
        self.data = data
        coord0, count = self._bootstrap(data)
        self.count_off = coord0 - 10
        self.prefix = data[:coord0 - 6]
        self.sig = data[coord0 + 8:coord0 + 10]
        suffix_len = self._suffix_len(data, coord0)
        self.suffix_len = suffix_len

        # capture one template per symbol signature
        self.templates = {}          # sigkey -> dict
        self.default_sig = None
        pos = coord0
        for k in range(count):
            sigkey = self._obj_sig(data, pos)
            label_start = pos + 0x28
            lab_end = data.index(b'\x00', label_start)
            if sigkey not in self.templates:
                self.templates[sigkey] = dict(
                    head=bytearray(data[pos - 6:label_start]),
                    suffix=data[lab_end + 1:lab_end + 1 + suffix_len],
                    lenfield0=struct.unpack_from('<H', data, pos + 0x26)[0],
                    label0_len=lab_end - label_start,
                    oid0=struct.unpack_from('<I', data, pos + 0x16)[0],
                )
            if self.default_sig is None:
                self.default_sig = sigkey
            pos = lab_end + 1 + suffix_len + 6
        self.footer = data[pos - 6:]
        self.symval_shapes = _detect_symval_shapes(data) if has_symbol else {}

    def _obj_sig(self, data, pos):
        symval = struct.unpack_from('<H', data, pos + 0x12)[0]
        try:
            le = data.index(b'\x00', pos + 0x28)
            ap = data.find(b'Arial', le)
            builtin = struct.unpack_from('<H', data, ap - 4)[0] if ap > 0 else 0xFFFF
        except ValueError:
            builtin = 0xFFFF
        if builtin != 0xFFFF:
            return ('B', builtin)
        return ('C', symval)

    def _suffix_len(self, data, coord0):
        lab_end = data.index(b'\x00', coord0 + 0x28)
        nxt = self._next_obj(data, lab_end + 1)
        if nxt is not None:
            return nxt - 6 - (lab_end + 1)
        return self.SUFFIX_LEN[self.has_symbol]

    @staticmethod
    def _geographic(data, i):
        if i + 8 > len(data):
            return False
        X = struct.unpack_from('<I', data, i)[0]
        Y = struct.unpack_from('<I', data, i + 4)[0]
        if not (0x40000000 < X < 0x60000000 and 0x60000000 < Y < 0x70000000):
            return False
        lon = (X - S31) / S23
        lat = (S31 - Y) / S23
        return -180 < lon < 180 and -85 < lat < 85

    def _bootstrap(self, data):
        i = 0
        while True:
            j = data.find(self.MARKER, i)
            if j < 0:
                raise ValueError("no point objects found")
            coord0 = j + 6
            if self._geographic(data, coord0) and coord0 >= 10:
                count = struct.unpack_from('<I', data, coord0 - 10)[0]
                if 0 < count < 1_000_000 and self._validate(data, coord0, count):
                    return coord0, count
            i = j + 1

    def _next_obj(self, data, frm):
        i = frm
        while True:
            j = data.find(self.MARKER, i)
            if j < 0:
                return None
            c = j + 6
            if self._geographic(data, c) and data[c + 8:c + 10] == self.sig:
                return c
            i = j + 1

    def _validate(self, data, coord0, count):
        sig = data[coord0 + 8:coord0 + 10]
        self.sig = sig
        try:
            lab0_end = data.index(b'\x00', coord0 + 0x28)
        except ValueError:
            return False
        nxt = self._next_obj(data, lab0_end + 1)
        suffix_len = (nxt - 6 - (lab0_end + 1)) if nxt else None
        pos = coord0
        for k in range(count):
            if data[pos - 6:pos] != self.MARKER or not self._geographic(data, pos):
                return False
            if data[pos + 8:pos + 10] != sig:
                return False
            try:
                le = data.index(b'\x00', pos + 0x28)
            except ValueError:
                return False
            if suffix_len is None:
                return k == count - 1
            pos = le + 1 + suffix_len + 6
        return True

    def build(self, points, sig_fn):
        out = bytearray(self.prefix)
        struct.pack_into('<I', out, self.count_off, len(points))
        oid = self.templates[self.default_sig]['oid0']
        for pm in points:
            sigkey = sig_fn(pm) if self.has_symbol else self.default_sig
            tpl = self.templates.get(sigkey) or self.templates[self.default_sig]
            lon, lat = pm.coords[0]
            X, Y = enc(lon, lat)
            label = (pm.name or '').encode('latin1', 'replace')
            blob = bytearray(tpl['head'])
            struct.pack_into('<I', blob, 6 + 0x00, X)
            struct.pack_into('<I', blob, 6 + 0x04, Y)
            if self.has_symbol and isinstance(sigkey, tuple) and sigkey[0] == 'C':
                struct.pack_into('<H', blob, 6 + 0x12, sigkey[1])
            struct.pack_into('<I', blob, 6 + 0x16, oid & 0xFFFFFFFF)
            lenf = tpl['lenfield0'] + (len(label) - tpl['label0_len'])
            struct.pack_into('<H', blob, 6 + 0x26, lenf & 0xFFFF)
            out += blob + label + b'\x00' + tpl['suffix']
            oid += 1
        out += self.footer
        struct.pack_into('<I', out, 0, len(out) - 4)
        return bytes(out)


# ----------------------------------------------------------------------------
# Polyline layer template (Centerline / Access)
# ----------------------------------------------------------------------------
class LineLayerTemplate:
    LINECOUNT_OFF = 0x14

    def __init__(self, data):
        n_lines = struct.unpack_from('<I', data, self.LINECOUNT_OFF)[0]
        first = self.LINECOUNT_OFF + 4
        self.prefix = data[:first]
        pos = first
        head0 = None
        for li in range(n_lines):
            vc_off = self._vtxcount_off(data, pos)
            if head0 is None:
                head0 = data[pos:vc_off]
            n = struct.unpack_from('<I', data, vc_off)[0]
            pos = vc_off + 4 + n * 16
        self.footer = data[pos:]
        self.linehead = bytearray(head0)
        self.color_rel = self._color_rel(self.linehead)
        self.oid_rel = 4
        self.ts_rels = self._timestamp_rels(self.linehead)

    @staticmethod
    def _vtxcount_off(data, line_start):
        i, end = line_start, len(data) - 16
        while i < end:
            if data[i:i + 2] == b'\x02\x00':
                vc = struct.unpack_from('<I', data, i + 2)[0]
                if data[i + 6:i + 12] == b'\x01\x00\x00\x00\x00\x00' and 0 < vc < 5_000_000:
                    return i + 2
            i += 1
        raise ValueError("vtxcount not found")

    @staticmethod
    def _color_rel(head):
        # colour is the 4 bytes immediately before the line-style field 03 00 00 00
        idx = bytes(head).rfind(b'\x03\x00\x00\x00')
        return idx - 4 if idx >= 4 else None

    @staticmethod
    def _timestamp_rels(head):
        # The real per-line timestamps sit after the marker(4)+oid(4) header.
        # Scanning from 0 would false-match the '..00 41 <oid>' marker bytes and
        # corrupt the object type, so start past the header.
        offs = []
        for i in range(12, len(head) - 8):
            v = struct.unpack_from('<I', head, i)[0]
            if 0x60000000 < v < 0x80000000 and head[i + 4:i + 8] == b'\x00\x00\x00\x00':
                offs.append(i)
        return offs

    def build(self, lines, color_fn):
        out = bytearray(self.prefix)
        struct.pack_into('<I', out, self.LINECOUNT_OFF, len(lines))
        oid = 0x7626
        ts = int(time.time())
        for pm in lines:
            head = bytearray(self.linehead)
            if self.color_rel is not None:
                r, g, b = color_fn(pm)
                head[self.color_rel:self.color_rel + 4] = bytes((r, g, b, 0))
            struct.pack_into('<I', head, self.oid_rel, oid & 0xFFFFFFFF)
            for off in self.ts_rels:
                struct.pack_into('<I', head, off, ts & 0xFFFFFFFF)
            verts = bytearray()
            for (lon, lat) in pm.coords:
                X, Y = enc(lon, lat)
                verts += b'\x01\x00\x00\x00\x00\x00' + struct.pack('<I', X) + struct.pack('<I', Y) + b'\x00\x00'
            out += head + struct.pack('<I', len(pm.coords)) + verts
            oid += 1
        out += self.footer
        struct.pack_into('<I', out, 0, len(out) - 4)
        return bytes(out)


# ----------------------------------------------------------------------------
# AGM icon -> symbol signature
# ----------------------------------------------------------------------------
def make_agm_sig_resolver(agm_template):
    shapes = agm_template.symval_shapes        # {symval: 'triangle'/'flag'/'circle'}
    shape_to_symval = {v: k for k, v in shapes.items()}
    tri = shape_to_symval.get('triangle')
    flag = shape_to_symval.get('flag')
    circle = shape_to_symval.get('circle')

    def resolve(pm):
        icon = (pm.icon or '').lower()
        if 'triangle' in icon and tri is not None:
            return ('C', tri)
        if 'flag' in icon and flag is not None:
            return ('C', flag)
        if ('circle' in icon or 'blu' in icon or 'paddle' in icon or 'dot' in icon) and circle is not None:
            return ('C', circle)
        return agm_template.default_sig
    return resolve


# ----------------------------------------------------------------------------
# Top level
# ----------------------------------------------------------------------------
def _template_bytes():
    return base64.b64decode(_TEMPLATE_B64)


def generate_dmt(kmz_path_or_bytes):
    folders = parse_kmz(kmz_path_or_bytes)
    tpl = OLE(_template_bytes())
    streams = tpl.stream_map()
    new_streams = {}

    for folder_name, stream_name in LAYER_STREAMS.items():
        items = folders.get(folder_name, [])
        tdata = streams[stream_name]
        if folder_name in ('AGMs', 'Notes'):
            pts = [p for p in items if p.kind == 'point']
            if not pts:
                continue
            t = PointLayerTemplate(tdata, has_symbol=(folder_name == 'AGMs'))
            if folder_name == 'AGMs':
                resolver = make_agm_sig_resolver(t)
            else:
                resolver = None
            new_streams[stream_name] = t.build(pts, resolver)
        else:
            lns = [p for p in items if p.kind == 'line']
            if not lns:
                continue
            t = LineLayerTemplate(tdata)

            def color_fn(pm, fld=folder_name):
                rgb = kml_color_to_rgb(pm.color)
                if rgb:
                    return rgb
                return (255, 0, 0) if fld == 'Centerline' else (0, 0, 255)
            new_streams[stream_name] = t.build(lns, color_fn)

    # Rename layers to clean names + rewrite the Annotate index streams.
    rename = {
        'Final AGMs68': 'AGMs',
        'Combined Access Files1 (11)': 'Access',
        'notes (26)': 'Notes',
        'Centerline41 (4)': 'Centerline',
    }
    order = ['Centerline41 (4)', 'notes (26)',
             'Combined Access Files1 (11)', 'Final AGMs68']
    layer_names = [rename[o] for o in order]
    new_streams['Annotate.Filenames'] = _filenames_stream('AGMs', layer_names)
    new_streams['Annotate.ActiveFilenames'] = _active_stream('AGMs')
    return write_ole(tpl, new_streams, rename=rename)


DRAW_DIR = r'C:\DeLorme Docs\Draw'


def _lp(s):
    b = s.encode('latin1', 'replace')
    return struct.pack('<I', len(b)) + b


def _filenames_stream(active_name, layer_names):
    out = bytearray()
    out += struct.pack('<I', 1)
    out += _lp(DRAW_DIR + '\\' + active_name + '.an1')
    out += struct.pack('<I', len(layer_names))
    for nm in layer_names:
        out += _lp(nm) + struct.pack('<I', 1)
    return bytes(out)


def _active_stream(active_name):
    return struct.pack('<I', 1) + _lp(DRAW_DIR + '\\' + active_name + '.an1')





# ----------------------------------------------------------------------------
# Centerline-only additions (new code; everything above is the proven core)
# ----------------------------------------------------------------------------
def _first_text(el, path):
    f = el.find(path, KNS)
    return f.text.strip() if f is not None and f.text else None


def _style_line_color(style_el):
    """LineStyle color from a Style element, falling back to any color."""
    if style_el is None:
        return None
    c = style_el.find('.//k:LineStyle/k:color', KNS)
    if c is None or not c.text:
        c = style_el.find('.//k:color', KNS)
    return c.text.strip() if c is not None and c.text else None


def _parse_kml_forgiving(raw):
    """Parse KML that may not be strictly well-formed.

    Real-world exports (e.g. ArcGIS "Export To KMZ") sometimes reference
    undeclared namespace prefixes like ``xsi:schemaLocation``, which the strict
    stdlib parser rejects ("unbound prefix"). Fall back to lxml's recovering
    parser, then round-trip through tostring so the rest of the code keeps
    working with plain xml.etree elements.
    """
    try:
        return ET.fromstring(raw)
    except ET.ParseError:
        from lxml import etree as _lxml

        parser = _lxml.XMLParser(recover=True, ns_clean=True, huge_tree=True)
        root = _lxml.fromstring(raw, parser=parser)
        if root is None:
            raise
        # recover=True keeps attributes whose prefix was never declared
        # (stored with a literal "prefix:name" key); drop them so the
        # re-serialized document is well-formed for the stdlib parser.
        for el in root.iter():
            if not isinstance(el.tag, str):
                continue
            for k in list(el.attrib):
                if not k.startswith('{') and ':' in k:
                    del el.attrib[k]
        return ET.fromstring(_lxml.tostring(root))


def extract_line_placemarks(kml_or_kmz_bytes):
    """All LineStrings in a KMZ/KML (document order) as line Placemarks.

    Handles MultiGeometry, placemarks outside folders, inline styles,
    shared styles, and StyleMap (normal key). Color is the KML aabbggrr
    LineStyle color string, or None if the document does not specify one.
    """
    raw = kml_or_kmz_bytes
    if isinstance(raw, (bytes, bytearray)) and raw[:2] == b'PK':
        raw = _read_kml_bytes(bytes(raw))
    root = _parse_kml_forgiving(raw)

    styles, stylemaps = {}, {}
    for el in root.iter():
        tag = _ln(el)
        if tag == 'Style' and el.get('id'):
            styles[el.get('id')] = el
        elif tag == 'StyleMap' and el.get('id'):
            for pair in el.findall('k:Pair', KNS):
                if _first_text(pair, 'k:key') in (None, 'normal'):
                    su = _first_text(pair, 'k:styleUrl')
                    if su:
                        stylemaps[el.get('id')] = su.lstrip('#')
                    st_inline = pair.find('k:Style', KNS)
                    if st_inline is not None:
                        styles['\x00map:' + el.get('id')] = st_inline
                        stylemaps.setdefault(el.get('id'), '\x00map:' + el.get('id'))
                    break

    def resolve_color(pm):
        if pm is None:
            return None
        color = _style_line_color(pm.find('k:Style', KNS))
        if color:
            return color
        su = _first_text(pm, 'k:styleUrl')
        seen = set()
        while su:
            sid = su.lstrip('#')
            if sid in seen:
                break
            seen.add(sid)
            if sid in styles:
                return _style_line_color(styles[sid])
            su = stylemaps.get(sid)
        return None

    parent = {c: p for p in root.iter() for c in p}

    def enclosing_placemark(el):
        while el is not None:
            if _ln(el) == 'Placemark':
                return el
            el = parent.get(el)
        return None

    out = []
    for ls in root.iter():
        if _ln(ls) != 'LineString':
            continue
        coords_el = ls.find('k:coordinates', KNS)
        if coords_el is None or not coords_el.text:
            continue
        coords = _coords(coords_el.text)
        if len(coords) < 2:
            continue
        pm = enclosing_placemark(ls)
        name = _first_text(pm, 'k:name') if pm is not None else None
        out.append(Placemark(name, 'line', coords, None, resolve_color(pm)))
    return out


def generate_centerline_dmt(line_placemarks):
    """Build a .dmt whose Centerline draw layer holds the given lines.

    Mirrors generate_dmt() exactly, but takes pre-extracted line placemarks
    (possibly from several KMZs) instead of one foldered KMZ, writes them all
    into the Centerline layer, and makes Centerline the active draw layer.
    Each line keeps its own KML color; lines without a color are red.
    """
    lns = [p for p in line_placemarks if p.kind == 'line' and len(p.coords) >= 2]
    if not lns:
        raise ValueError('No LineString geometry to write into the .dmt.')

    tpl = OLE(_template_bytes())
    streams = tpl.stream_map()

    t = LineLayerTemplate(streams['Centerline41 (4)'])

    def color_fn(pm):
        rgb = kml_color_to_rgb(pm.color)
        return rgb if rgb else (255, 0, 0)

    new_streams = {'Centerline41 (4)': t.build(lns, color_fn)}

    # Rebuild the other three draw layers as EMPTY (zero objects) so none of
    # the template's example content (AGM symbols, key-map notes, access
    # lines) shows up in the output — only the centerline geometry remains.
    new_streams['Final AGMs68'] = PointLayerTemplate(
        streams['Final AGMs68'], has_symbol=True).build([], None)
    new_streams['notes (26)'] = PointLayerTemplate(
        streams['notes (26)'], has_symbol=False).build([], None)
    new_streams['Combined Access Files1 (11)'] = LineLayerTemplate(
        streams['Combined Access Files1 (11)']).build([], None)

    rename = {
        'Final AGMs68': 'AGMs',
        'Combined Access Files1 (11)': 'Access',
        'notes (26)': 'Notes',
        'Centerline41 (4)': 'Centerline',
    }
    order = ['Centerline41 (4)', 'notes (26)',
             'Combined Access Files1 (11)', 'Final AGMs68']
    layer_names = [rename[o] for o in order]
    new_streams['Annotate.Filenames'] = _filenames_stream('Centerline', layer_names)
    new_streams['Annotate.ActiveFilenames'] = _active_stream('Centerline')
    return write_ole(tpl, new_streams, rename=rename)
